name: Update from Upstream

on:
  repository_dispatch:
    types: [update-from-upstream]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repository
        uses: actions/checkout@v2

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Alvin9999/pac2
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories  # Allow merging unrelated histories
          git push origin master  # Push changes to 'master'
