name: Sync Upstream Repository

on:
  schedule:
    - cron: '0 * * * *'  # Run the workflow every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Sync with upstream
      run: |
        git remote add upstream https://github.com/Alvin9999/pac2.git
        git fetch upstream
        git checkout master
        git merge upstream/master
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
